stages:
  process_data:
    cmd: ./run_pipeline.sh --prepare
    deps:
    - data/dataset.parquet
    - scripts/data/preprocess.py
    outs:
    - data/test_finetune.parquet
    - data/test_pretrain.parquet
    - data/test_twhin.parquet
    - data/train_finetune.parquet
    - data/train_pretrain.parquet
    - data/train_twhin.parquet
